blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/wotzebra/filament-media-library/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Support question
    url: https://github.com/wotzebra/filament-media-library/discussions/new?category=q-a
    about: Ask the community for help
  - name: Report a security issue
    url: https://github.com/wotzebra/filament-media-library/README.md#security
    about: Learn how to notify us for sensitive bugs
  - name: Report a bug
    url: https://github.com/wotzebra/filament-media-library/issues/new
    about: Report a reproducable bug
